---
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
  - name: install prerequsitist    
    apt: name={{ item }} state=latest update_cache=yes
    loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    
  - name: add docker gpg key
    ansible-builtin.apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: add docker repo
    ansible.builtin.apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
      state: present

  - name: install apps
    package:
      name: htop
      name: ssh
      name: firefox-esr
      name: docker-ce
      name: docker-ce-cli
      name: containerd.io
