---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install apps
    package:
      name: htop
      name: ssh
      name: firefox-esr
      name: docker-ce
      name: docker-ce-cli
      name: containerd.io
