---
- hosts: localhost
  connection: local
  become: true
  become_user: root

  tasks:
  - name: update apt repo cache
    apt:
      update_cache: yes
      
  - name: update apt package
    apt:
      available: yes
      upgrade: yes
      
  - name: install prerequsitist    
    apt:
      name: pt-transport-https,ca-certificates,curl,gnupg-agent,software-properties-common
      state: latest

  - name: add docker gpg key
    apt_key:
      url: https://download.docker.com/linux/debian/gpg
      state: present

  - name: add docker repo
    apt_repository:
      repo: deb https://download.docker.com/linux/debian buster stable
      state: present

  - name: update apt repo cache
    apt:
      update_cache: yes

  - name: install apps
    apt:
      name: htop,ssh,firefox-esr,docker-ce,docker-ce-cli,containerd.io
